package Vista;


import Modelo.NegocioDAO;
import Modelo.SistemaDAO;
import static Vista.MDI.jDesktopPane1;
import java.util.ArrayList;
import javax.swing.SwingConstants;

/**
 *
 * @author alexc
 */
public class JIFAdmin extends javax.swing.JInternalFrame {

    public JIFAdmin() {
        initComponents();
        NegocioDAO negInfo = new NegocioDAO();
        informacionNegocio = negInfo.mostrarInfoNegocio();
        SistemaDAO sisInfo = new SistemaDAO();
        informacionSistema = sisInfo.mostrarInfoSistema();
       
        lblNitNegocio.setText(informacionNegocio.get(0));
        lblNombreNegocio.setText(informacionNegocio.get(1));
        lblResoNegocio.setText(informacionSistema.get(0));
        lblFechaAutoRS.setText(informacionSistema.get(2));
        lblNombreNegocio.setHorizontalAlignment(SwingConstants.CENTER);
        lblNombreNegocio.setVerticalAlignment(SwingConstants.CENTER);
        controlVentanaAdmin = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnModeloResolucion = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        lblNombreNegocio = new javax.swing.JLabel();
        lblDE = new javax.swing.JLabel();
        lblResolucionText = new javax.swing.JLabel();
        lblResoNegocio = new javax.swing.JLabel();
        lblNitNegocioText = new javax.swing.JLabel();
        lblFechaAutoRS = new javax.swing.JLabel();
        lblNitNegocio = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Administracion");
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setForeground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Taurus", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Administracion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 340, -1));

        btnModeloResolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JFAdmin_modeloResolucion.png"))); // NOI18N
        btnModeloResolucion.setBorder(null);
        btnModeloResolucion.setContentAreaFilled(false);
        btnModeloResolucion.setFocusPainted(false);
        btnModeloResolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModeloResolucionActionPerformed(evt);
            }
        });
        jPanel1.add(btnModeloResolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 120, 140));

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JFAdmin_Clientes.png"))); // NOI18N
        btnClientes.setBorder(null);
        btnClientes.setContentAreaFilled(false);
        btnClientes.setFocusPainted(false);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 120, 140));

        btnHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JFAdmin_HISTORIAL.png"))); // NOI18N
        btnHistorial.setBorder(null);
        btnHistorial.setContentAreaFilled(false);
        btnHistorial.setFocusPainted(false);
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        jPanel1.add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 120, 140));

        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JFAdmin_Ventas.png"))); // NOI18N
        btnVentas.setBorder(null);
        btnVentas.setContentAreaFilled(false);
        btnVentas.setFocusPainted(false);
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 120, 140));

        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JFAdmin_Inventario.png"))); // NOI18N
        btnInventario.setBorder(null);
        btnInventario.setContentAreaFilled(false);
        btnInventario.setFocusPainted(false);
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 120, 140));

        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JFAdmin_Compras.png"))); // NOI18N
        btnCompras.setBorder(null);
        btnCompras.setContentAreaFilled(false);
        btnCompras.setFocusPainted(false);
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });
        jPanel1.add(btnCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 120, 140));

        lblNombreNegocio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombreNegocio.setForeground(new java.awt.Color(255, 255, 0));
        lblNombreNegocio.setText("DATOS DE EMPRESA Y ADMINISTRADOR");
        jPanel1.add(lblNombreNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 360, 30));

        lblDE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDE.setForeground(new java.awt.Color(255, 255, 0));
        lblDE.setText("de");
        jPanel1.add(lblDE, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 20, 30));

        lblResolucionText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblResolucionText.setForeground(new java.awt.Color(255, 255, 0));
        lblResolucionText.setText("Resolución");
        jPanel1.add(lblResolucionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 90, 30));

        lblResoNegocio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblResoNegocio.setForeground(new java.awt.Color(255, 255, 0));
        lblResoNegocio.setText("123456789123456");
        jPanel1.add(lblResoNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 160, 30));

        lblNitNegocioText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNitNegocioText.setForeground(new java.awt.Color(255, 255, 0));
        lblNitNegocioText.setText("NIT:");
        jPanel1.add(lblNitNegocioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 40, 30));

        lblFechaAutoRS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFechaAutoRS.setForeground(new java.awt.Color(255, 255, 0));
        lblFechaAutoRS.setText("66666666");
        jPanel1.add(lblFechaAutoRS, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 110, 30));

        lblNitNegocio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNitNegocio.setForeground(new java.awt.Color(255, 255, 0));
        lblNitNegocio.setText("66666666");
        jPanel1.add(lblNitNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 110, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JFAdmi_fondoPanel.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static boolean controlVentanaAdmin = false;
    public static ArrayList<String> informacionNegocio = new ArrayList<String>();
    public static ArrayList<String> informacionSistema = new ArrayList<String>();


    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        
        if (JIFClientes.controlVentanaClientes) { //SI YA ESTA ACTIVA UNA VENTANA DE CLIENTES, NO ABRIR OTRA
            return;
        }

        JIFClientes vistaC = new JIFClientes();
        vistaC.setLocation(((jDesktopPane1.getSize()).width - (vistaC.getSize()).width) / 2, ((jDesktopPane1.getSize()).height - (vistaC.getSize()).height) / 2);
        jDesktopPane1.add(vistaC);
        vistaC.toFront();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        if (JIFHistorial.controlVentanaHistorial) { //SI YA ESTA ACTIVA UNA VENTANA, NO ABRIR OTRA
            return;
        }

        JIFHistorial vistaH = new JIFHistorial();
        vistaH.setLocation(((jDesktopPane1.getSize()).width - (vistaH.getSize()).width) / 2, ((jDesktopPane1.getSize()).height - (vistaH.getSize()).height) / 2);
        jDesktopPane1.add(vistaH);
        vistaH.toFront();
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        if (JIFVentas.controlVentanaVentas) { //SI YA ESTA ACTIVA UNA VENTANA, NO ABRIR OTRA
            return;
        }

        JIFVentas vistaV = new JIFVentas();
        vistaV.setLocation(((jDesktopPane1.getSize()).width - (vistaV.getSize()).width) / 2, ((jDesktopPane1.getSize()).height - (vistaV.getSize()).height) / 2);
        jDesktopPane1.add(vistaV);
        vistaV.toFront();
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        if (JIFInventario.controlVentanaInventario) { //SI YA ESTA ACTIVA UNA VENTANA, NO ABRIR OTRA
            return;
        }

        JIFInventario vistaI = new JIFInventario();
        vistaI.setLocation(((jDesktopPane1.getSize()).width - (vistaI.getSize()).width) / 2, ((jDesktopPane1.getSize()).height - (vistaI.getSize()).height) / 2);
        jDesktopPane1.add(vistaI);
        vistaI.toFront();
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        if (JIFCompras.controlVentanaCompras) { //SI YA ESTA ACTIVA UNA VENTANA, NO ABRIR OTRA
            return;
        }

        JIFCompras vistaCom = new JIFCompras();
        vistaCom.setLocation(((jDesktopPane1.getSize()).width - (vistaCom.getSize()).width) / 2, ((jDesktopPane1.getSize()).height - (vistaCom.getSize()).height) / 2);
        jDesktopPane1.add(vistaCom);
        vistaCom.toFront();
    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnModeloResolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModeloResolucionActionPerformed

        if (JIFModeloResolucion.controlVentanaModeloResolucion) { //SI YA ESTA ACTIVA UNA VENTANA, NO ABRIR OTRA
            return;
        }

        JIFModeloResolucion vistaMR = new JIFModeloResolucion();
        vistaMR.setLocation(((jDesktopPane1.getSize()).width - (vistaMR.getSize()).width) / 2, ((jDesktopPane1.getSize()).height - (vistaMR.getSize()).height) / 2);
        jDesktopPane1.add(vistaMR);
        vistaMR.toFront();
    }//GEN-LAST:event_btnModeloResolucionActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        controlVentanaAdmin = false;
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        jDesktopPane1.revalidate();
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnInventario;
    public static javax.swing.JButton btnModeloResolucion;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel fondo;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lblDE;
    public static javax.swing.JLabel lblFechaAutoRS;
    public static javax.swing.JLabel lblNitNegocio;
    public static javax.swing.JLabel lblNitNegocioText;
    private javax.swing.JLabel lblNombreNegocio;
    public static javax.swing.JLabel lblResoNegocio;
    public static javax.swing.JLabel lblResolucionText;
    // End of variables declaration//GEN-END:variables
}
