package Vista;

import Controlador.ControladorCliente;
import Modelo.ClienteDAO;
import Modelo.Conexion;
import com.mxrck.autocompleter.AutoCompleterCallback;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author alexc
 */
public class JIFClientes extends javax.swing.JInternalFrame {

    static public boolean controlVentanaClientes;
    private TextAutoCompleter ac;
    public static ArrayList<String> informacionCliente = new ArrayList<String>();

    public JIFClientes() {
        initComponents();
        controlVentanaClientes = true;
        formatearTablaClientes();

        /*CONFIGURACIONES PARA LA LISTA/BUSCADOR*/
        ac = new TextAutoCompleter(txtNit, new AutoCompleterCallback() {
            @Override
            public void callback(Object selectedItem) {
                informacionCliente = null;
                ClienteDAO c = new ClienteDAO();
                informacionCliente = c.mostrarInfoCliente(String.valueOf(selectedItem));
                txtNombre.setText(informacionCliente.get(0));
                txtDomicilio.setText(informacionCliente.get(1));

            }
        });

        ClienteDAO c = new ClienteDAO();
        c.mostrarNitsDeClientes(ac);

    }

    private void formatearTablaClientes() {

        this.TablaClientes.setShowGrid(true);
        this.TablaClientes.setShowVerticalLines(true);
        this.TablaClientes.setShowHorizontalLines(true);

        //CENTRAR EL HEADER DE LAS COLUMNAS
        DefaultTableCellRenderer headersResoluciones = (DefaultTableCellRenderer) this.TablaClientes.getTableHeader().getDefaultRenderer();
        headersResoluciones.setHorizontalAlignment(0);
        //CENTRAR LAS CELDAS
        DefaultTableCellRenderer celdasResoluciones = new DefaultTableCellRenderer();
        celdasResoluciones.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < 3; i++) {
            this.TablaClientes.getColumnModel().getColumn(i).setCellRenderer(celdasResoluciones);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNit = new javax.swing.JTextField();
        txtDomicilio = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnRegistrarCliente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnRefrescarClientes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();
        fondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Clientes");
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Taurus", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Clientes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, -1));

        jLabel2.setFont(new java.awt.Font("Taurus", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Domicilio:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, -1));

        jLabel3.setFont(new java.awt.Font("Taurus", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("NIT:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 60, -1));

        jLabel4.setFont(new java.awt.Font("Taurus", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, -1));
        jPanel1.add(txtNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 170, -1));
        jPanel1.add(txtDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 170, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 170, -1));

        btnRegistrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ButtonSave.png"))); // NOI18N
        btnRegistrarCliente.setBorderPainted(false);
        btnRegistrarCliente.setContentAreaFilled(false);
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 140, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clientesIcon.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 160, 130));

        btnRefrescarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/refresh.png"))); // NOI18N
        btnRefrescarClientes.setBorderPainted(false);
        btnRefrescarClientes.setContentAreaFilled(false);
        btnRefrescarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarClientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefrescarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 40, 40));

        TablaClientes.setBackground(new java.awt.Color(255, 255, 159));
        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NIT", "NOMBRE", "DOMICILIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaClientes.setSelectionBackground(new java.awt.Color(0, 153, 255));
        jScrollPane1.setViewportView(TablaClientes);
        if (TablaClientes.getColumnModel().getColumnCount() > 0) {
            TablaClientes.getColumnModel().getColumn(0).setResizable(false);
            TablaClientes.getColumnModel().getColumn(1).setResizable(false);
            TablaClientes.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 660, 190));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JIFClientes.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        controlVentanaClientes = false;
    }//GEN-LAST:event_formInternalFrameClosing

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed

        if (txtNit.getText().equals("")) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Indicar el numero de NIT");
            return;
        }

        if (txtNombre.getText().equals("")) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Especificar un nombre");
            return;
        }

        if (txtDomicilio.getText().equals("")) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Especificar un domicilio");
            return;
        }

        ControladorCliente cCli = new ControladorCliente(txtNombre.getText(), txtDomicilio.getText(), JIFAdmin.lblNitNegocio.getText(), txtNit.getText());
        cCli.crearCliente(cCli);
        ClienteDAO c = new ClienteDAO();
        c.mostrarNitsDeClientes(ac);
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnRefrescarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarClientesActionPerformed
        DefaultTableModel dtmClientes = (DefaultTableModel) this.TablaClientes.getModel();
        dtmClientes.setRowCount(0);

        ArrayList<Object[]> clientesObtenidos = new ArrayList<>();
        ClienteDAO c = new ClienteDAO();
        clientesObtenidos = c.mostrarClientes();

        for (int i = 0; i < clientesObtenidos.size(); i++) {
            dtmClientes.addRow(clientesObtenidos.get(i));
        }

    }//GEN-LAST:event_btnRefrescarClientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaClientes;
    private javax.swing.JButton btnRefrescarClientes;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
